@RheaGymManagment.Api_HostAddress = http://localhost:5119

@host=http://localhost:5119
@adminId=ea51ccef-090d-4ce8-9faa-a358e88a4613

# GET {{host}}/weatherforecast/
# Accept: application/json

POST {{host}}/Subscription
Content-Type: application/json

{
  "SubscriptionType": "Pro",
  "AdminId": "{{adminId}}"
}

###

POST {{host}}/subscriptions/95D139E3-924D-45BE-887F-3A4C74CA5497/gyms
Content-Type: application/json

{
  "name": "Bu",
  "subscriptionId": "95D139E3-924D-45BE-887F-3A4C74CA5497"
}